apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka-local-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storageclass
  local:
    path: /home/ubuntu/airflow/kafka
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - bami-node1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: spark-local-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storageclass
  local:
    path: /home/ubuntu/airflow/spark
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - bami-node1
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-local-pvc
  namespace: airflow
spec:
  storageClassName: local-storageclass
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: kafka-local-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spark-local-pvc
  namespace: airflow
spec:
  storageClassName: local-storageclass
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: spark-local-pv
