apiVersion: v1
kind: Pod
metadata:
  name: kafka-client
  namespace: kafka
spec:
  containers:
  - name: kafka-client
    image: confluentinc/cp-kafka:7.6.0
    command:
      - sh
      - -c
      - "exec tail -f /dev/null"
