apiVersion: v1
kind: PersistentVolume
metadata:
  name: zookeeper
  labels:
    resource/type: pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: cp-storageclass
  hostPath:
    path: /data/zookeeper
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: kafka
  labels:
    resource/type: pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: cp-storageclass
  hostPath:
    path: /data/kafka
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-longinus-pa-prod-zookeeper-0
  labels:
    resource/type: pvc
  namespace: kafka
spec:
  storageClassName: cp-storageclass
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  volumeName: zookeeper
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-0-longinus-pa-prod-kafka-0
  labels:
    resource/type: pvc
  namespace: kafka
spec:
  storageClassName: cp-storageclass
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  volumeName: kafka
